// Generated by gencpp from file nodelet_rosbag/SubscribeGoal.msg
// DO NOT EDIT!


#ifndef NODELET_ROSBAG_MESSAGE_SUBSCRIBEGOAL_H
#define NODELET_ROSBAG_MESSAGE_SUBSCRIBEGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nodelet_rosbag
{
template <class ContainerAllocator>
struct SubscribeGoal_
{
  typedef SubscribeGoal_<ContainerAllocator> Type;

  SubscribeGoal_()
    : topics()  {
    }
  SubscribeGoal_(const ContainerAllocator& _alloc)
    : topics(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _topics_type;
  _topics_type topics;





  typedef boost::shared_ptr< ::nodelet_rosbag::SubscribeGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nodelet_rosbag::SubscribeGoal_<ContainerAllocator> const> ConstPtr;

}; // struct SubscribeGoal_

typedef ::nodelet_rosbag::SubscribeGoal_<std::allocator<void> > SubscribeGoal;

typedef boost::shared_ptr< ::nodelet_rosbag::SubscribeGoal > SubscribeGoalPtr;
typedef boost::shared_ptr< ::nodelet_rosbag::SubscribeGoal const> SubscribeGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nodelet_rosbag::SubscribeGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nodelet_rosbag::SubscribeGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nodelet_rosbag

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nodelet_rosbag': ['/home/punnu/catkin_ws/devel/share/nodelet_rosbag/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nodelet_rosbag::SubscribeGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nodelet_rosbag::SubscribeGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nodelet_rosbag::SubscribeGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nodelet_rosbag::SubscribeGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nodelet_rosbag::SubscribeGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nodelet_rosbag::SubscribeGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nodelet_rosbag::SubscribeGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b0eef9a05d4e829092fc2f2c3c2aad3d";
  }

  static const char* value(const ::nodelet_rosbag::SubscribeGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb0eef9a05d4e8290ULL;
  static const uint64_t static_value2 = 0x92fc2f2c3c2aad3dULL;
};

template<class ContainerAllocator>
struct DataType< ::nodelet_rosbag::SubscribeGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nodelet_rosbag/SubscribeGoal";
  }

  static const char* value(const ::nodelet_rosbag::SubscribeGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nodelet_rosbag::SubscribeGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
string[] topics\n\
";
  }

  static const char* value(const ::nodelet_rosbag::SubscribeGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nodelet_rosbag::SubscribeGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.topics);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SubscribeGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nodelet_rosbag::SubscribeGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nodelet_rosbag::SubscribeGoal_<ContainerAllocator>& v)
  {
    s << indent << "topics[]" << std::endl;
    for (size_t i = 0; i < v.topics.size(); ++i)
    {
      s << indent << "  topics[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.topics[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NODELET_ROSBAG_MESSAGE_SUBSCRIBEGOAL_H
