// Generated by gencpp from file nodelet_rosbag/SubscribeFeedback.msg
// DO NOT EDIT!


#ifndef NODELET_ROSBAG_MESSAGE_SUBSCRIBEFEEDBACK_H
#define NODELET_ROSBAG_MESSAGE_SUBSCRIBEFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nodelet_rosbag
{
template <class ContainerAllocator>
struct SubscribeFeedback_
{
  typedef SubscribeFeedback_<ContainerAllocator> Type;

  SubscribeFeedback_()
    : status(0)  {
    }
  SubscribeFeedback_(const ContainerAllocator& _alloc)
    : status(0)  {
  (void)_alloc;
    }



   typedef int32_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::nodelet_rosbag::SubscribeFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nodelet_rosbag::SubscribeFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct SubscribeFeedback_

typedef ::nodelet_rosbag::SubscribeFeedback_<std::allocator<void> > SubscribeFeedback;

typedef boost::shared_ptr< ::nodelet_rosbag::SubscribeFeedback > SubscribeFeedbackPtr;
typedef boost::shared_ptr< ::nodelet_rosbag::SubscribeFeedback const> SubscribeFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nodelet_rosbag::SubscribeFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nodelet_rosbag::SubscribeFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nodelet_rosbag

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nodelet_rosbag': ['/home/punnu/catkin_ws/devel/share/nodelet_rosbag/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nodelet_rosbag::SubscribeFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nodelet_rosbag::SubscribeFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nodelet_rosbag::SubscribeFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nodelet_rosbag::SubscribeFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nodelet_rosbag::SubscribeFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nodelet_rosbag::SubscribeFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nodelet_rosbag::SubscribeFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "86791dcf1de997ec7de5a0de7e4dcfcc";
  }

  static const char* value(const ::nodelet_rosbag::SubscribeFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x86791dcf1de997ecULL;
  static const uint64_t static_value2 = 0x7de5a0de7e4dcfccULL;
};

template<class ContainerAllocator>
struct DataType< ::nodelet_rosbag::SubscribeFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nodelet_rosbag/SubscribeFeedback";
  }

  static const char* value(const ::nodelet_rosbag::SubscribeFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nodelet_rosbag::SubscribeFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
int32 status\n\
\n\
";
  }

  static const char* value(const ::nodelet_rosbag::SubscribeFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nodelet_rosbag::SubscribeFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SubscribeFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nodelet_rosbag::SubscribeFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nodelet_rosbag::SubscribeFeedback_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NODELET_ROSBAG_MESSAGE_SUBSCRIBEFEEDBACK_H
