; Auto-generated. Do not edit!


(cl:in-package nodelet_rosbag-msg)


;//! \htmlinclude RecordResult.msg.html

(cl:defclass <RecordResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass RecordResult (<RecordResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RecordResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RecordResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name nodelet_rosbag-msg:<RecordResult> is deprecated: use nodelet_rosbag-msg:RecordResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RecordResult>) ostream)
  "Serializes a message object of type '<RecordResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RecordResult>) istream)
  "Deserializes a message object of type '<RecordResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RecordResult>)))
  "Returns string type for a message object of type '<RecordResult>"
  "nodelet_rosbag/RecordResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RecordResult)))
  "Returns string type for a message object of type 'RecordResult"
  "nodelet_rosbag/RecordResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RecordResult>)))
  "Returns md5sum for a message object of type '<RecordResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RecordResult)))
  "Returns md5sum for a message object of type 'RecordResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RecordResult>)))
  "Returns full string definition for message of type '<RecordResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RecordResult)))
  "Returns full string definition for message of type 'RecordResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RecordResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RecordResult>))
  "Converts a ROS message object to a list"
  (cl:list 'RecordResult
))
