; Auto-generated. Do not edit!


(cl:in-package nodelet_rosbag-msg)


;//! \htmlinclude RecordGoal.msg.html

(cl:defclass <RecordGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass RecordGoal (<RecordGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RecordGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RecordGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name nodelet_rosbag-msg:<RecordGoal> is deprecated: use nodelet_rosbag-msg:RecordGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RecordGoal>) ostream)
  "Serializes a message object of type '<RecordGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RecordGoal>) istream)
  "Deserializes a message object of type '<RecordGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RecordGoal>)))
  "Returns string type for a message object of type '<RecordGoal>"
  "nodelet_rosbag/RecordGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RecordGoal)))
  "Returns string type for a message object of type 'RecordGoal"
  "nodelet_rosbag/RecordGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RecordGoal>)))
  "Returns md5sum for a message object of type '<RecordGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RecordGoal)))
  "Returns md5sum for a message object of type 'RecordGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RecordGoal>)))
  "Returns full string definition for message of type '<RecordGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RecordGoal)))
  "Returns full string definition for message of type 'RecordGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RecordGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RecordGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'RecordGoal
))
