; Auto-generated. Do not edit!


(cl:in-package nodelet_rosbag-msg)


;//! \htmlinclude StartResult.msg.html

(cl:defclass <StartResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass StartResult (<StartResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StartResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StartResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name nodelet_rosbag-msg:<StartResult> is deprecated: use nodelet_rosbag-msg:StartResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StartResult>) ostream)
  "Serializes a message object of type '<StartResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StartResult>) istream)
  "Deserializes a message object of type '<StartResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StartResult>)))
  "Returns string type for a message object of type '<StartResult>"
  "nodelet_rosbag/StartResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StartResult)))
  "Returns string type for a message object of type 'StartResult"
  "nodelet_rosbag/StartResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StartResult>)))
  "Returns md5sum for a message object of type '<StartResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StartResult)))
  "Returns md5sum for a message object of type 'StartResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StartResult>)))
  "Returns full string definition for message of type '<StartResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StartResult)))
  "Returns full string definition for message of type 'StartResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StartResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StartResult>))
  "Converts a ROS message object to a list"
  (cl:list 'StartResult
))
