; Auto-generated. Do not edit!


(cl:in-package nodelet_rosbag-msg)


;//! \htmlinclude StopResult.msg.html

(cl:defclass <StopResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass StopResult (<StopResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StopResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StopResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name nodelet_rosbag-msg:<StopResult> is deprecated: use nodelet_rosbag-msg:StopResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StopResult>) ostream)
  "Serializes a message object of type '<StopResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StopResult>) istream)
  "Deserializes a message object of type '<StopResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StopResult>)))
  "Returns string type for a message object of type '<StopResult>"
  "nodelet_rosbag/StopResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StopResult)))
  "Returns string type for a message object of type 'StopResult"
  "nodelet_rosbag/StopResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StopResult>)))
  "Returns md5sum for a message object of type '<StopResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StopResult)))
  "Returns md5sum for a message object of type 'StopResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StopResult>)))
  "Returns full string definition for message of type '<StopResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StopResult)))
  "Returns full string definition for message of type 'StopResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StopResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StopResult>))
  "Converts a ROS message object to a list"
  (cl:list 'StopResult
))
