; Auto-generated. Do not edit!


(cl:in-package nodelet_rosbag-msg)


;//! \htmlinclude SubscribeResult.msg.html

(cl:defclass <SubscribeResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass SubscribeResult (<SubscribeResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SubscribeResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SubscribeResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name nodelet_rosbag-msg:<SubscribeResult> is deprecated: use nodelet_rosbag-msg:SubscribeResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SubscribeResult>) ostream)
  "Serializes a message object of type '<SubscribeResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SubscribeResult>) istream)
  "Deserializes a message object of type '<SubscribeResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SubscribeResult>)))
  "Returns string type for a message object of type '<SubscribeResult>"
  "nodelet_rosbag/SubscribeResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SubscribeResult)))
  "Returns string type for a message object of type 'SubscribeResult"
  "nodelet_rosbag/SubscribeResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SubscribeResult>)))
  "Returns md5sum for a message object of type '<SubscribeResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SubscribeResult)))
  "Returns md5sum for a message object of type 'SubscribeResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SubscribeResult>)))
  "Returns full string definition for message of type '<SubscribeResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SubscribeResult)))
  "Returns full string definition for message of type 'SubscribeResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SubscribeResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SubscribeResult>))
  "Converts a ROS message object to a list"
  (cl:list 'SubscribeResult
))
