// Generated by gencpp from file robotnik_pp_msgs/GoToFeedback.msg
// DO NOT EDIT!


#ifndef ROBOTNIK_PP_MSGS_MESSAGE_GOTOFEEDBACK_H
#define ROBOTNIK_PP_MSGS_MESSAGE_GOTOFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotnik_pp_msgs
{
template <class ContainerAllocator>
struct GoToFeedback_
{
  typedef GoToFeedback_<ContainerAllocator> Type;

  GoToFeedback_()
    : percent_complete(0.0)  {
    }
  GoToFeedback_(const ContainerAllocator& _alloc)
    : percent_complete(0.0)  {
  (void)_alloc;
    }



   typedef float _percent_complete_type;
  _percent_complete_type percent_complete;





  typedef boost::shared_ptr< ::robotnik_pp_msgs::GoToFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotnik_pp_msgs::GoToFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct GoToFeedback_

typedef ::robotnik_pp_msgs::GoToFeedback_<std::allocator<void> > GoToFeedback;

typedef boost::shared_ptr< ::robotnik_pp_msgs::GoToFeedback > GoToFeedbackPtr;
typedef boost::shared_ptr< ::robotnik_pp_msgs::GoToFeedback const> GoToFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotnik_pp_msgs::GoToFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotnik_pp_msgs::GoToFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotnik_pp_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'robotnik_pp_msgs': ['/home/punnu/catkin_ws/src/robotnik_purepursuit_planner/robotnik_pp_msgs/msg', '/home/punnu/catkin_ws/devel/share/robotnik_pp_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_pp_msgs::GoToFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotnik_pp_msgs::GoToFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotnik_pp_msgs::GoToFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotnik_pp_msgs::GoToFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_pp_msgs::GoToFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotnik_pp_msgs::GoToFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotnik_pp_msgs::GoToFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d342375c60a5a58d3bc32664070a1368";
  }

  static const char* value(const ::robotnik_pp_msgs::GoToFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd342375c60a5a58dULL;
  static const uint64_t static_value2 = 0x3bc32664070a1368ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotnik_pp_msgs::GoToFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotnik_pp_msgs/GoToFeedback";
  }

  static const char* value(const ::robotnik_pp_msgs::GoToFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotnik_pp_msgs::GoToFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define a feedback message\n\
float32 percent_complete\n\
\n\
";
  }

  static const char* value(const ::robotnik_pp_msgs::GoToFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotnik_pp_msgs::GoToFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percent_complete);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotnik_pp_msgs::GoToFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotnik_pp_msgs::GoToFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percent_complete: ";
    Printer<float>::stream(s, indent + "  ", v.percent_complete);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTNIK_PP_MSGS_MESSAGE_GOTOFEEDBACK_H
