// Auto-generated. Do not edit!

// (in-package robotnik_pp_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let goal = require('./goal.js');

//-----------------------------------------------------------

class GoToGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.target = null;
    }
    else {
      if (initObj.hasOwnProperty('target')) {
        this.target = initObj.target
      }
      else {
        this.target = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type GoToGoal
    // Serialize message field [target]
    // Serialize the length for message field [target]
    bufferOffset = _serializer.uint32(obj.target.length, buffer, bufferOffset);
    obj.target.forEach((val) => {
      bufferOffset = goal.serialize(val, buffer, bufferOffset);
    });
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type GoToGoal
    let len;
    let data = new GoToGoal(null);
    // Deserialize message field [target]
    // Deserialize array length for message field [target]
    len = _deserializer.uint32(buffer, bufferOffset);
    data.target = new Array(len);
    for (let i = 0; i < len; ++i) {
      data.target[i] = goal.deserialize(buffer, bufferOffset)
    }
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += 28 * object.target.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'robotnik_pp_msgs/GoToGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '5c7eeba8aff53a215446e596e2937594';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the goal
    goal[] target
    
    ================================================================================
    MSG: robotnik_pp_msgs/goal
    # Position 
    geometry_msgs/Pose2D pose
    # Desired speed
    float32 speed
    
    ================================================================================
    MSG: geometry_msgs/Pose2D
    # Deprecated
    # Please use the full 3D pose.
    
    # In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.
    
    # If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.
    
    
    # This expresses a position and orientation on a 2D manifold.
    
    float64 x
    float64 y
    float64 theta
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new GoToGoal(null);
    if (msg.target !== undefined) {
      resolved.target = new Array(msg.target.length);
      for (let i = 0; i < resolved.target.length; ++i) {
        resolved.target[i] = goal.Resolve(msg.target[i]);
      }
    }
    else {
      resolved.target = []
    }

    return resolved;
    }
};

module.exports = GoToGoal;
